# Generated by Django 3.2.7 on 2021-09-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210925_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('home', 'home'), ('sports', 'sports'), ('clothings', 'clothings'), ('books', 'books'), ('others', 'others')], max_length=10),
        ),
    ]
