# Generated by Django 3.2.7 on 2021-09-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('sports', 'Sports'), ('clothings', 'Clothings'), ('books', 'Books'), ('others', 'Others')], max_length=10),
        ),
    ]
